#!/usr/bin/python

# Variables
topology_path = "/home/noel/Projects/Protein_design/EntropyMaxima/params/charmm27.ff/top_all27_prot_na.rtf"
parameter_path = "/home/noel/Projects/Protein_design/EntropyMaxima/params/charmm27.ff/par_all27_prot_na.prm"
nina_rad_path = "/home/noel/Projects/Protein_design/EntropyMaxima/params/charmm27.ff/radii_prot_na_dfg.str"
# Fix headers
main_header = "* Auto-generated CHARMM script.\n*\n! CHARMM input generated by charmm_setup.py\n!==========================="
top_header = "! Read in topology and parameter files\n! ====================================\n"

# topology, typeR = rtf
# parameter, typeR = para
def read_unit(action,numb,path,typeR):
    return "open "+action+" unit "+str(numb)+" card name \""+path+"\"\n"+action+" "+typeR+" card unit 1\nclose unit "+str(numb)

def nina_radii(path):
    return "stream \""+path+"\""

print(read_unit("read",1,topology_path,"rtf"))
print(read_unit("read",1,parameter_path,"para"))
print(nina_radii(nina_rad_path))

open read unit 1 card name C.SEQ
read sequence unit 1 card
close unit 1
generate C first ACE last CTER setup 
stream "C_FIXRES.INP"

open read unit 1 card name F.SEQ
read sequence unit 1 card
close unit 1
generate F first ACE last CTER setup
stream "F_FIXRES.INP"

!patch disu A 6 A 11 setup sort warn
!patch disu A 7 B 7 sort warn
!patch disu A 20 B 19 sort warn

scalar wmain = charge

open write unit 1 card name 1brs_comp_1rr.psf
write psf card unit 1

open write unit 1 card name 1brs_comp_1rr.ic
write ic card unit 1

open read unit 1 card name 1brs_comp_1r.crd 
read coor card unit 1 resid
close unit 1

! Check for and build in missing heavy atoms
! Build is done into default geometry from parameter file.
! ==========================================

define missing1 sele .not. ( init .or. hydrogen ) end
if ?nsel ne 0 print coor sele .not. ( init .or. hydrogen ) end

ic param
ic fill preserve
ic build

define missing2 sele .not. ( init .or. hydrogen ) end
if ?nsel ne 0 print coor sele .not. ( init .or. hydrogen ) end

! Build hydrogens
! Default parameters are rdiel of 4, with no cutoffs.
! ===================================================

hbuild sele hydrogen end -
  elec atom rdiel switch eps 2 -
  vdw vatom vswitch -
  cutnb 999 ctofnb 998 ctonnb 997 wmin 1.5 -
  e14fac 1 nbxmod 5

hbuild sele hydrogen end -
  elec atom rdiel switch eps 2 -
  vdw vatom vswitch -
  cutnb 999 ctofnb 998 ctonnb 997 wmin 1.5 -
  e14fac 1 nbxmod 5

update

! Write out structure, ic table and coordinates.
! ==============================================

scalar wmain = charge

open write unit 1 card name 1brs_comp_1rr.crd
write coor card unit 1

open write unit 1 card name 1brs_comp_1rr.pdb
write coor pdb unit 1

write psf card xplo name 1brs_comp_1rr_xplo.psf

stop

! End generated CHARMM input
! ==========================
